import { ResolvedEquipment, ResolvedOpening, WallEdge } from '../types.js';
import { ResolvedArchilang, VwExportOptions, VwScript } from './vw-types.js';

const DEFAULT_OPTIONS: Required<VwExportOptions> = {
  layer: '平面-1F',
  defaultWallClass: '建築-壁-新設',
  origin: { x: 0, y: 0 },
  flipY: true,
};

const WALL_CLASS_BY_TOKEN = [
  { tokens: ['existing', 'exist', '既存'], className: '建築-壁-既存' },
  { tokens: ['demo', 'demol', 'remove', '解体'], className: '建築-壁-解体' },
  { tokens: ['new', '新設'], className: '建築-壁-新設' },
] as const;

export function emitVwPython(model: ResolvedArchilang, options: VwExportOptions = {}): VwScript {
  const config: Required<VwExportOptions> = {
    layer: options.layer ?? DEFAULT_OPTIONS.layer,
    defaultWallClass: options.defaultWallClass ?? DEFAULT_OPTIONS.defaultWallClass,
    origin: options.origin ?? DEFAULT_OPTIONS.origin,
    flipY: options.flipY ?? DEFAULT_OPTIONS.flipY,
  };

  const walls = [...model.walls].sort((a, b) => a.id.localeCompare(b.id));
  const openings = [...model.openings].sort((a, b) => a.id.localeCompare(b.id));
  const equipment = [...model.equipment].sort((a, b) => a.id.localeCompare(b.id));
  const generatedAt = new Date().toISOString();

  const lines: string[] = [];
  lines.push('# -*- coding: utf-8 -*-');
  lines.push('# Generated by archilang-laporta VW Marionette emitter');
  lines.push(`# Generated at: ${generatedAt}`);
  lines.push(`# Walls: ${walls.length}, Doors: ${countDoors(openings)}, Windows: ${countWindows(openings)}, Equipment: ${equipment.length}`);
  lines.push('import vs');
  lines.push('');
  lines.push('def _safe_reset_orientation() -> None:');
  lines.push("    if hasattr(vs, 'ResetOrientation3D'):");
  lines.push('        try:');
  lines.push('            vs.ResetOrientation3D()');
  lines.push('        except Exception:');
  lines.push('            pass');
  lines.push('');
  lines.push(`vs.Layer(${pythonString(config.layer)})`);
  lines.push(`vs.SetActLayer(${pythonString(config.layer)})`);
  lines.push(`vs.NameClass(${pythonString(config.defaultWallClass)})`);
  lines.push('');
  lines.push('# Walls');

  for (const wall of walls) {
    const wallClass = resolveWallClass(wall, config.defaultWallClass);
    const p1 = transformPoint(wall.x1, wall.y1, model, config);
    const p2 = transformPoint(wall.x2, wall.y2, model, config);

    lines.push(`vs.NameClass(${pythonString(wallClass)})`);
    lines.push(
      `vs.AddWall((${formatNumber(p1.x)}, ${formatNumber(p1.y)}), (${formatNumber(p2.x)}, ${formatNumber(p2.y)}))  # ${wall.id}`
    );
  }

  if (openings.length > 0) {
    lines.push('');
    lines.push('# Openings');
  }

  for (const opening of openings) {
    const className = resolveOpeningClass(opening);
    const point = transformPoint(opening.cx, opening.cy, model, config);
    const summary = [
      `${opening.type === 'AW' ? 'Window' : 'Door'} ${opening.id}`,
      `wall=${opening.wallId}`,
      `x=${formatNumber(point.x)}`,
      `y=${formatNumber(point.y)}`,
      `width=${formatNumber(opening.w)}`,
      `height=${formatNumber(opening.h)}`,
      `style=${opening.style}`,
    ];
    if (opening.sill !== undefined) {
      summary.push(`sill=${formatNumber(opening.sill)}`);
    }

    lines.push(`vs.NameClass(${pythonString(className)})`);
    lines.push(`# ${summary.join(', ')}`);
  }

  if (model.skippedOpenings.length > 0) {
    lines.push('');
    lines.push('# Skipped openings');
    for (const skipped of model.skippedOpenings) {
      lines.push(`# Skipped ${skipped.id}: ${skipped.reasonCode} - ${skipped.reason}`);
    }
  }

  if (equipment.length > 0) {
    lines.push('');
    lines.push('# Equipment');
  }

  for (const item of equipment) {
    const point = transformPoint(item.x, item.y, model, config);
    lines.push(
      `# Equipment ${item.id}: type=${item.type}, wall=${item.wallId}, x=${formatNumber(point.x)}, y=${formatNumber(point.y)}, w=${formatNumber(item.w)}, h=${formatNumber(item.h)}`
    );
  }

  lines.push('');
  lines.push('_safe_reset_orientation()');
  lines.push('');

  return {
    filename: buildFilename(model),
    pythonCode: lines.join('\n'),
    meta: {
      wallCount: walls.length,
      doorCount: countDoors(openings),
      windowCount: countWindows(openings),
      equipmentCount: equipment.length,
      generatedAt,
    },
  };
}

function buildFilename(model: ResolvedArchilang): string {
  const totalAreaM2 = (model.totalGridX * model.moduleSize * model.totalGridY * model.moduleSize) / 1_000_000;
  const rounded = Math.max(1, Math.round(totalAreaM2));
  return `archilang-${rounded}sqm.py`;
}

function resolveWallClass(wall: WallEdge, fallback: string): string {
  const searchable = `${wall.id} ${wall.source ?? ''}`.toLowerCase();
  for (const entry of WALL_CLASS_BY_TOKEN) {
    if (entry.tokens.some(token => searchable.includes(token))) {
      return entry.className;
    }
  }
  return fallback;
}

function resolveOpeningClass(opening: ResolvedOpening): string {
  if (opening.type === 'AW') {
    const searchable = `${opening.id} ${opening.style}`.toLowerCase();
    return searchable.includes('existing') || searchable.includes('既存')
      ? '窓-既存'
      : '窓-新設';
  }

  const searchable = `${opening.id} ${opening.style}`.toLowerCase();
  if (searchable.includes('アルミ')) {
    return '建具-アルミ';
  }
  if (searchable.includes('鋼')) {
    return '建具-鋼製';
  }
  return '建具-木製';
}

function transformPoint(
  x: number,
  y: number,
  model: ResolvedArchilang,
  options: Required<VwExportOptions>
): { x: number; y: number } {
  const totalHeight = model.totalGridY * model.moduleSize;
  const transformedY = options.flipY
    ? totalHeight - y + options.origin.y
    : y + options.origin.y;

  return {
    x: x + options.origin.x,
    y: transformedY,
  };
}

function countDoors(openings: ResolvedOpening[]): number {
  return openings.filter(opening => opening.type === 'WD' || opening.type === 'AD').length;
}

function countWindows(openings: ResolvedOpening[]): number {
  return openings.filter(opening => opening.type === 'AW').length;
}

function formatNumber(value: number): string {
  if (Number.isInteger(value)) {
    return `${value}`;
  }
  return `${Math.round(value * 1000) / 1000}`;
}

function pythonString(value: string): string {
  return JSON.stringify(value);
}
